name: uno11
root: dos22

# start session with this window open
startup_window: code

windows:
  - code:
      panes:
        - tres333
  - server:
      layout: even-vertical
      panes:
        - cd layout
        - cd layout
  - build:
      layout: even-vertical
      panes:
        - quatro444
        - quatro444
  - files:
      panes:
        - quatro444
  - terminal:
      panes:
        - #
